name: first-action
on: push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: hello-world
        run: echo "Hello World. This is my first workflow run"
      - name: bteq-version
        run: which bteq
